In [1]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
# Number of axis
a.ndim 

2

In [4]:
a.dtype.name

'int32'

In [5]:
# Number of bits occupied by each element
a.itemsize

4

In [10]:
a.size

15

In [35]:
# Creating an array using list
b= np.array([32,3,5])
print(b)

[32  3  5]


In [8]:
# Creating array using tuple
c= np.array((12,23,43))
c

array([12, 23, 43])

In [11]:
# describing type of elements in an array
b.dtype

dtype('int32')

In [13]:
c.itemsize

4

In [16]:
b2=np.array([(12,23,4.3),(32,42,1)])
b2


array([[12. , 23. ,  4.3],
       [32. , 42. ,  1. ]])

In [18]:
# we can also explicitly specify type of array at creation time
c2=np.array([[1,2],[3,4]],dtype=complex)
c2

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [31]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [34]:
np.empty((2,3))

array([[12. , 23. ,  4.3],
       [32. , 42. ,  1. ]])

If the array is too large to be printed, Numpy automatically skips central part and only prints the corners

In [38]:
                       #2 matrix,each with 3 rows,4 columns
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Basic operations

In [43]:
# 1.
a=np.array([12,22,33,44])
b=np.arange(4)
b

array([0, 1, 2, 3])

In [45]:
c=a-b
c

array([12, 21, 31, 41])

In [47]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [48]:
a<20

array([ True, False, False, False])

Matrix multiplication

In [50]:
a=np.array([[1,2],[2,3]])
b=np.array([[3,4],[4,0]])
a*b #elementwise product

array([[3, 8],
       [8, 0]])

In [51]:
a@b #matrix product

array([[11,  4],
       [18,  8]])

In [52]:
a.dot(b) #matrix product

array([[11,  4],
       [18,  8]])

In [53]:
a.min()

1

In [54]:
b= np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
b.sum(axis=0)  # sum of each column

array([12, 15, 18, 21])

In [56]:
b.min(axis=1) #min of each row

array([0, 4, 8])

In [57]:
b.sum(axis=1)

array([ 6, 22, 38])

In [59]:
b.cumsum(axis=1)  #cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)